'use strict'

const fs = require('fs')

const ora = require('ora')
const got = require('got')
const cheerio = require('cheerio')

const spinner = ora('Fetching from npmjs.com...')
spinner.start()

const npmPopular = async () => {
  try {
    const res = await got('npmjs.com')
    const list = parseBody(res.body)
    spinner.stop()
    writeToFile(list)
  } catch (e) {
    console.log(e.response.body)
  }
}

const parseBody = (body) => {
  const $ = cheerio.load(body)
  const libArray = $('.marginalia-container').find('h3')

  const list = []
  libArray.each((index, el) => {
    const item = $(el).find('a')
    const name = item.text()
    const url = `npmjs.com${item.attr('href')}`

    list.push({ name, url })
  })

  return list
}

const writeToFile = (list) => {
  const output = fs.createWriteStream('Popular')

  output.write('# The most popular node modules in npmjs.com.\n\n')
  for (const nm of list) {
    output.write(`${nm.name} => ${nm.url}\n`)
  }
  output.end('\n# Generated by npm-popular.\n')

  console.log('Write into Popular successfully.')
}

module.exports = npmPopular
